import { UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Summe from "~/components/Summe";

import Image from "next/image";

import { api } from "~/utils/api";
import { Entry } from "~/components/Entry";
import { InputForm } from "~/components/InputForm";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { data } = api.posts.getAll.useQuery();

  const { user } = useUser();
  if (!user) return;

  const firstname = user.firstName;
  const lastname = user.lastName;
  const email = user.emailAddresses[0]?.emailAddress;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      <div className="flex items-center justify-between bg-black p-4">
        <Image src="/Logo.png" alt="Logo" width={59.44} height={50} />
        <div className="flex items-center gap-5">
          <UserButton afterSignOutUrl="/" />
          <Image src="/NameLogo.png" alt="NameLogo" width={150} height={100} />
        </div>
      </div>
      <main className="flex min-h-screen flex-col items-center bg-[url('/Background.jpg')] bg-cover bg-fixed">
        <p className="pt-4 text-black">
          You are logged in as: {firstname} {lastname}, {email}
        </p>
        <div className="container p-4">
          <Entry price={4} tip={2} />
          <Entry price={4} tip={2} />
          <Entry price={4} tip={2} />
          <Entry price={4} tip={2} />
          <Summe />
          <div className="absolute bottom-1 left-1/2 -translate-x-1/2 -translate-y-1/2 transform">
            <InputForm />
          </div>
        </div>
        {/* <Link
            className="flex max-w-xs flex-col gap-4 rounded-xl bg-black/50 p-4 text-white"
            href="https://create.t3.gg/en/usage/first-steps"
            target="_blank"
          >
            <h3 className="text-2xl font-bold">First Steps →</h3>
          </Link>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          <div>
            {data?.map((post) => <div key={post.id}>{post.comment}</div>)}
          </div> */}
      </main>
    </>
  );
}
