import { UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Summe from "~/components/Summe";

import Image from "next/image";

import { api } from "~/utils/api";
import { InputForm } from "~/components/InputForm";
import { EntryList } from "~/components/EntryList";

export default function Home() {
  const entries = api.entries.getAll.useQuery();
  const { user } = useUser();

  if (!user) return;

  const email = user.emailAddresses[0]?.emailAddress;
  if (!email) return;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-[url('/Background.jpg')] bg-cover bg-fixed">
        <div className="flex min-w-full items-center justify-between bg-black p-4">
          <Image src="/Logo.png" alt="Logo" width={59.44} height={50} />
          <div className="flex items-center gap-5">
            <UserButton afterSignOutUrl="/" />
            <Image
              priority
              src="/NameLogo.png"
              alt="NameLogo"
              width={150}
              height={100}
            />
          </div>
        </div>
        <div className="max-w-xs p-4">
          <div>
            <EntryList
              entries={entries.data}
              isLoading={entries.isLoading}
              isError={entries.isError}
            />
            <Summe />
          </div>
        </div>
        <div className="absolute bottom-4 max-w-xs p-4">
          <InputForm />
        </div>
      </main>
    </>
  );
}
